<?php require_once "twig_instance.php";
require 'layout.php';
require 'sidebar-middle-high-school.php';
$page=array(
	'metaTitle'=>'',
    'metaDescription'=>'',
    'title' => 'EMPLOYMENT',
    'time' => 'TIME',
    'activity' => 'ACTIVITY',
    'content' =>'<div id="bodtxt" class="text-justify">
		<h4 class="text-center">Working at the International American School of Cancun</h4>
		<p><img style="float:right; margin:10px;" src="static/img/employment/1.jpg" width="230" height="188" class="pixrgt">The  International American School of Cancun is looking for dedicated professionals  willing to overcome the frustrations of living abroad, living in a city that  does not all the amenities of American cities, and working at a school which  does not have the resources, equipment and support personnel an older school  would have. Cancun, although a wonderful city with great beaches and impressive  historical areas, is not a city with many resources. Some important supplies  may not be available on a regular basis and the quality of materials may be inferior to those found in the U.S. (For example, we do not have a  great variety of paper and furniture, the tape may not stick as well, etc.) The  students, parents and administrators depend on teachers who are willing and  able to do a good job without these amenities. It is a challenge that is not  easy on a daily basis.</p>
		<p><img style="float:left; margin:10px;" src="static/img/employment/employ2.jpg" width="175" height="188" class="pixlft">There are many  cultural differences that North Americans, in general, find difficult to deal  with on a daily basis. People often arrive late for appointments, look up  childbearing differently and standards of efficiency are different. The  International American School of Cancun is a growing project serving a  community that is also international. It requires understanding staff members willing  to dedicate themselves to something that will someday be an important facet of  the community. We need commitment, dedication, and enthusiasm, and offer in  exchange an experience in another culture, a tropical location, and an  opportunity to make one place in the world a little better.</p>
		<p>Adapting to a  different culture requires exceptional flexibility. Relocating to another  county means a different language and a different set of customs, which may  cause frustrations and misunderstandings. The responsibility to adapt will be  yours, not that of the citizens of the host country. Your ability to adapt will  be your most important guideline, perhaps more important than your past  experiences. The presence or absence of this characteristic will be a very  important factor in your work as a teacher in an overseas American school. You  will be living in a foreign country and representing both the United States and  the International American School during your stay. Although working in Mexico  is challenging, it is also very rewarding!</p>
		<p>We invite you  to contact us to learn more about working at the International American School  of Cancun. We are regularly recruiting and interviewing candidates for 7-12  teaching and administrative positions. All applications are welcome. Please send  us an email at: <a href="mailto:inquiries@iasces.com">inquiries@iasces.com</a> with both your cover letter and resume attached.</p>
		<p>The International  American School of Cancun adheres to a policy of nondiscrimination in  employment and educational programs/activities and strives affirmatively to  provide equal opportunity for all. &nbsp;We prohibit&nbsp;discrimination  against employees or applicants on the basis of sex, race, color, ethnic or  national origin, religion, marital status, disability, genetic information,  age, political beliefs, sexual orientation, gender, gender identification,  social and family background, linguistic preference, pregnancy, and any other  legally prohibited basis. </p>
		<h1 class="text-center"><img src="static/img/employment/employ3.jpg" width="500" height="289"></h1></div>'
);
echo $twig->render('middle-high-school-employment.html',array('main_menu'=>$main_menu,'footer'=>$footer,'sidebar'=>$sidebar,'page'=>$page));
?>